version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rinhadebackend
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine-perl
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - db
    depends_on:
      - db

#  app:
#    image: my-spring-app:latest
#    ports:
#      - 8080:8080
#    depends_on:
#      - db

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1